# Generated by Django 5.2.4 on 2025-10-22 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.TextField()),
                ('name_en', models.TextField()),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_es', models.TextField()),
                ('title_en', models.TextField()),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopicIsAboutConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.concept')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.topic')),
            ],
            options={
                'ordering': ['order_id'],
                'unique_together': {('topic', 'concept', 'order_id')},
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='concepts',
            field=models.ManyToManyField(related_name='topics', through='content.TopicIsAboutConcept', to='content.concept'),
        ),
        migrations.CreateModel(
            name='Epigraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.TextField()),
                ('name_en', models.TextField()),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('order_id', models.IntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epigraphs', to='content.topic')),
            ],
            options={
                'ordering': ['order_id'],
                'unique_together': {('id', 'topic')},
            },
        ),
    ]
