# Generated by Django 5.2.4 on 2025-10-22 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name_en',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_es',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='epigraph',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epigraphs', to='content.topic', unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_en',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_es',
            field=models.TextField(unique=True),
        ),
    ]
