# Generated by Django 5.2.4 on 2025-11-25 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='concept',
            name='unique_active_concept_name_es',
        ),
        migrations.RemoveConstraint(
            model_name='concept',
            name='unique_active_concept_name_en',
        ),
    ]
