# Generated by Django 5.2.4 on 2025-11-26 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_concept_unique_active_concept_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conceptisrelatedtoconcept',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conceptisrelatedtoconcept',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
