# Generated by Django 5.2.4 on 2025-11-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_topicisaboutconcept_order_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('name_es', 'name_en'), name='unique_active_concept_name_es'),
        ),
    ]
