# Generated by Django 5.2.4 on 2025-10-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_concept_name_en_alter_concept_name_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epigraph',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epigraphs', to='content.topic'),
        ),
    ]
