# Generated by Django 5.2.4 on 2025-11-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_conceptisrelatedtoconcept_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='examples_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concept',
            name='examples_es',
            field=models.TextField(blank=True, null=True),
        ),
    ]
