# Generated by Django 5.2.4 on 2025-10-23 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_epigraph_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptIsRelatedToConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_concepts_from', to='content.concept')),
                ('concept_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_concepts_to', to='content.concept')),
            ],
            options={
                'unique_together': {('concept_from', 'concept_to')},
            },
        ),
    ]
