# Generated by Django 5.2.4 on 2025-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_concept_unique_active_concept_name_es'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='concept',
            name='unique_active_concept_name_es',
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('name_es',), name='unique_active_concept_name_es'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('name_en',), name='unique_active_concept_name_en'),
        ),
    ]
