# Generated by Django 5.2.4 on 2025-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_concept_examples_en_concept_examples_es'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name_en',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_es',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_en',
            field=models.TextField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_es',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
