# Generated by Django 5.2.4 on 2025-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_concept_unique_active_concept_name_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_es',
            field=models.TextField(),
        ),
    ]
