# Generated by Django 5.2.4 on 2025-10-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_conceptisrelatedtoconcept'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='related_concepts',
            field=models.ManyToManyField(related_name='related_to_concepts', through='content.ConceptIsRelatedToConcept', to='content.concept'),
        ),
    ]
