# Generated by Django 5.2.4 on 2025-11-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_concept_name_en_alter_concept_name_es'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='title_en',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_es',
            field=models.TextField(),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('title_es',), name='unique_active_topic_title_es'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('title_en',), name='unique_active_topic_title_en'),
        ),
    ]
