# Generated by Django 5.2.4 on 2025-12-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_concept_name_en_alter_concept_name_es_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='name_en',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name_es',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_en',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topic',
            name='title_es',
            field=models.TextField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('name_es',), name='unique_active_concept_name_es'),
        ),
        migrations.AddConstraint(
            model_name='concept',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('name_en',), name='unique_active_concept_name_en'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('title_es',), name='unique_active_topic_title_es'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('old', False)), fields=('title_en',), name='unique_active_topic_title_en'),
        ),
    ]
