export const STRINGS = {
  en: {
    appName: 'Student_iOrg',
    language: 'Language',
    joinGroup: 'Join a Group',
    join: 'Join',
    leaveGroup: 'Leave Group',
    subjectCode: 'Subject Code (e.g., ABC-123)',
    invalidCode: 'Invalid Code. Try again.',
    hexagonGame: 'Hexagon',
    exam: 'Exam',
    concepts: 'Concepts',
    headings: 'Headings',
    back: 'Back',
    generateExam: 'Generate Exam',
    selectTopics: 'Select topics for the exam:',
    numQuestions: 'Number of questions:',
    startExam: 'Start Exam',
    finishExam: 'Finish Exam',
    finishGame: 'Finish Hexagon',
    next: 'Next',
    previous: 'Previous',
    results: 'Results',
    score: 'Your score',
    recommendations: 'Recommendations',
    gameResultTitle: 'Resulting Organization',
    tapToReveal: 'Tap to reveal',
    timeRemaining: 'Time',
    error: 'Error',
    errorConnection: 'Connection error.',
    errorMinTopics: 'You must select at least one topic.',
    errorInvalidQuestions: 'Invalid number of questions.',
    examInProgress: 'Exam in progress',
    examInProgressMessage: 'You cannot leave without finishing the exam.',
    loading: 'Loading...',
    loadingGame: 'Loading game...',
    generatingExam: 'Generating exam...',
    pleaseSelectAnswer: 'Please select an answer before proceeding.',
    endRevision: 'End Revision',
    noRecommendations: 'Congratulations, there are no recommendations.',
  },
  es: {
    appName: 'Student_iOrg',
    language: 'Idioma',
    joinGroup: 'Únete a un Grupo',
    join: 'Unirse',
    leaveGroup: 'Salir del Grupo',
    subjectCode: 'Código de Asignatura (ej: ABC-123)',
    invalidCode: 'Código inválido. Inténtalo de nuevo.',
    hexagonGame: 'Hexágono',
    exam: 'Examen',
    concepts: 'Conceptos',
    headings: 'Epígrafes',
    back: 'Volver',
    generateExam: 'Generar Examen',
    selectTopics: 'Selecciona temas para el examen:',
    numQuestions: 'Número de preguntas:',
    startExam: 'Iniciar Examen',
    finishExam: 'Terminar Examen',
    finishGame: 'Terminar Hexágono',
    next: 'Siguiente',
    previous: 'Anterior',
    results: 'Resultados',
    score: 'Tu nota',
    recommendations: 'Recomendaciones',
    gameResultTitle: 'Organización Resultante',
    tapToReveal: 'Toca para revelar',
    timeRemaining: 'Tiempo',
    error: 'Error',
    errorConnection: 'Error de conexión.',
    errorMinTopics: 'Debes seleccionar al menos un tema.',
    errorInvalidQuestions: 'Número de preguntas inválido.',
    examInProgress: 'Examen en curso',
    examInProgressMessage: 'No puedes salir sin terminar el examen.',
    loading: 'Cargando...',
    loadingGame: 'Cargando juego...',
    generatingExam: 'Generando examen...',
    pleaseSelectAnswer: 'Por favor selecciona una respuesta antes de continuar.',
    endRevision: 'Terminar Revisión',
    noRecommendations: '¡Felicidades! No hay recomendaciones.',
  },
};
