# Generated by Django 5.2.4 on 2025-11-01 10:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.TextField(unique=True)),
                ('name_en', models.TextField(unique=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('old', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_es', models.TextField(unique=True)),
                ('name_en', models.TextField(unique=True)),
                ('groupCode', models.CharField(blank=True, max_length=20, null=True)),
                ('old', models.BooleanField(default=False)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studentgroups', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentgroups', to='courses.subject')),
            ],
            options={
                'unique_together': {('id', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='SubjectIsAboutTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content.topic')),
            ],
            options={
                'unique_together': {('subject', 'topic', 'order_id')},
            },
        ),
        migrations.CreateModel(
            name='TeacherMakeChangeStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.studentgroup')),
                ('old_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='courses.studentgroup')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('old_group', 'new_group', 'created_at', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='TeacherMakeChangeSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('new_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='courses.subject')),
                ('old_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='courses.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('old_subject', 'new_subject', 'created_at', 'teacher')},
            },
        ),
    ]
