# Generated by Django 5.2.4 on 2025-10-22 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_concept_name_en_alter_concept_name_es_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachermakechangestudentgroup',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='teachermakechangestudentgroup',
            name='name_es',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='studentCode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='SubjectIsAboutTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(unique=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='content.topic')),
            ],
            options={
                'unique_together': {('subject', 'topic', 'order_id')},
            },
        ),
    ]
