# Generated by Django 5.2.4 on 2025-10-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_teachermakechangestudentgroup_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectisabouttopic',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
