# Generated by Django 5.2.4 on 2025-10-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_subjectisabouttopic_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='studentCode',
            new_name='groupCode',
        ),
    ]
