export const STRINGS = {
  en: {
    login: "Login",
    email: "Email",
    password: "Password",
    appName: 'Teacher_iOrg',
    home: 'Home',
    manageGroups: 'Manage Groups',
    groupDetail: 'Group Detail',
    manageQuestions: 'Manage Questions',
    manageContent: 'Manage Content',
    statistics: 'Statistics',
    inviteTeacher: 'Invite Teacher',
    logs: 'Logs',
  },
  es: {
    login: "Iniciar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    appName: 'Teacher_iOrg',
    home: 'Inicio',
    manageGroups: 'Gestionar Grupos',
    groupDetail: 'Detalle del Grupo',
    manageQuestions: 'Gestionar Preguntas',
    manageContent: 'Gestionar Contenido',
    statistics: 'Estadísticas',
    inviteTeacher: 'Invitar Profesor',
    logs: 'Auditoría',
  },
};
