export const STRINGS = {
  en: {
    // --- General Actions & UI ---
    login: "Login",
    email: "Email",
    password: "Password",
    appName: 'Teacher_iOrg',
    home: 'Home',
    success: 'Success',
    error: 'Error',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    create: 'Create',
    delete: 'Delete',
    edit: 'Edit',
    back: 'Back',
    next: 'Next',
    loading: 'Loading...',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    actions: 'Actions',
    clean: 'Clean',
    filters: 'Filters',
    results: 'Results',
    noResults: 'No results found.',
    select: 'Selecting...',
    loadingData: 'Loading...',
    fillAllFields: 'Please fill in all fields.',

    // --- Dashboard ---
    panel: 'Teacher Panel',
    manageGroups: 'Manage Groups',
    manageQuestions: 'Manage Questions',
    manageContent: 'Manage Content',
    statistics: 'Statistics',
    inviteTeacher: 'Invite Teacher',
    logs: 'Logs',
    importExcel: 'Import Excel',
    importing: 'Importing data...',
    importSuccess: 'Content imported successfully.',
    importError: 'Failed to import content.',

    // --- Auth & Settings ---
    settings: 'Settings',
    language: 'Language',
    changePassword: 'Change Password',
    logout: 'Logout',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm New Password',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordChanged: 'Password updated successfully.',

    // --- Analytics ---
    performanceAnalytics: 'Performance Analytics',
    analyzeProgress: 'Analyze progress and statistics',
    configuration: 'Configuration',
    groupBy: 'Group View By',
    filterBySubject: 'Filter by Subject',
    allSubjects: 'All Subjects',
    clearFilter: 'Clear Filter',
    percentageCorrect: '% Correct',
    noData: 'Not enough data to display charts.',
    breakdown: 'Detailed Breakdown',
    hits: 'Hits',
    attempts: 'Attempts',
    selectSubject: 'Select Subject',
    globalReset: 'Global Reset',
    confirmGlobalReset: 'Are you sure you want to delete ALL statistics for ALL subjects? This empties the exam history.',
    topic: 'Topic',
    concept: 'Concept',
    group: 'Group',
    question: 'Question',

    // --- Backup ---
    backupManagement: 'Backup Management',
    generateBackup: 'Generate New Backup',
    noBackups: 'No backups available.',
    processing: 'Processing...',
    restoreConfirm: '⚠️ THIS WILL OVERWRITE ALL CURRENT DATA. Continue?',
    restoreSuccess: 'Restore completed successfully.',
    restoreFail: 'Restore failed.',
    downloadError: 'Could not download file.',
    auto: 'AUTO',
    manual: 'MANUAL',

    // --- Group Detail ---
    accessCode: 'Access Code',
    copyCode: 'Copy Code',
    shareCode: 'Share Code',
    codeCopied: 'Access code copied to clipboard.',
    viewStats: 'View Statistics',
    deleteGroup: 'Delete Group',
    deleteGroupConfirm: 'Are you sure you want to delete this group?',
    
    // --- Manage Groups ---
    teachingManagement: 'Teaching Management',
    subjects: 'Subjects',
    touchToOrder: 'Touch to order topics',
    myGroups: 'My Groups',
    otherGroups: 'Other Groups',
    noSubjects: 'No subjects available.',
    noGroups: 'You have not created any groups.',
    createGroup: 'Create Group',
    createSubject: 'Create Subject',
    newGroup: 'New Group',
    newSubject: 'New Subject',
    subject: 'Subject',
    groupName: 'Group Name',
    name: 'Name',
    description: 'Description',
    spanishVersion: '🇪🇸 Spanish Version',
    englishVersion: '🇬🇧 English Version',
    exampleGroup: 'Ex: Group A - Morning',
    exampleSubject: 'Ex: Mathematics',
    
    // --- Manage Content ---
    academicContent: 'Academic Content',
    topics: 'Topics',
    concepts: 'Concepts',
    noContent: 'No content created.',
    relatedTo: 'Related to',
    manageTopics: 'Manage Topics',
    linkedTopicsInfo: 'Selected topics appear first.',
    
    // --- Manage Questions ---
    questions: 'Questions',
    newQuestion: 'New Question',
    statement: 'Statement',
    context: 'Context',
    questionType: 'Question Type',
    multipleChoice: 'Multiple Choice',
    trueFalse: 'True / False',
    selectTopic: 'Select a topic.',
    selectTopicError: 'Select at least one topic.',
    answers: 'Answers',
    option: 'Option',
    addOption: 'Add Option',
    correct: 'Correct',
    missingStatement: 'Statement is mandatory.',
    missingCorrect: 'Mark at least one correct answer.',
    missingTranslation: 'Missing English translations.',
    saved: 'Saved successfully.',
    new: 'New',

    // --- Manage Users ---
    users: 'Users',
    manageInvite: 'Manage and invite new members',
    invite: 'Invite',
    createUser: 'Create User',
    username: 'Username',
    role: 'Role',
    admin: 'Administrator (SuperUser)',
    teacher: 'Teacher', // Used in modal
    accessDenied: 'Access Denied',
    noPerms: 'You do not have permissions to manage users.',
    deleteUserConfirm: 'Are you sure you want to delete',
    userCreated: 'User created. Temporary password:',
    tempPasswordHint: 'Temporary password: ',
    emailInvalid: 'Please enter a valid email.',
    passwordGenError: 'Could not generate password from email.',
    
    // --- Topic Detail ---
    epigraphs: 'Epigraphs',
    noEpigraphs: 'No epigraphs defined.',
    deleteEpigraphConfirm: 'Are you sure you want to delete this epigraph?',
  },
  es: {
    // --- General Actions & UI ---
    login: "Iniciar sesión",
    email: "Correo electrónico",
    password: "Contraseña",
    appName: 'Teacher_iOrg',
    home: 'Inicio',
    success: 'Éxito',
    error: 'Error',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    save: 'Guardar',
    create: 'Crear',
    delete: 'Eliminar',
    edit: 'Editar',
    back: 'Volver',
    next: 'Siguiente',
    loading: 'Cargando...',
    yes: 'Sí',
    no: 'No',
    ok: 'Vale',
    actions: 'Acciones',
    clean: 'Limpiar',
    filters: 'Filtros',
    results: 'Resultados',
    noResults: 'No hay resultados.',
    select: 'Seleccionando...',
    loadingData: 'Cargando...',
    fillAllFields: 'Por favor, completa todos los campos.',

    // --- Dashboard ---
    panel: 'Panel del Profesor',
    manageGroups: 'Gestionar Grupos',
    manageQuestions: 'Gestionar Preguntas',
    manageContent: 'Gestionar Contenido',
    statistics: 'Estadísticas',
    inviteTeacher: 'Invitar Profesor',
    logs: 'Copias de Seguridad',
    importExcel: 'Cargar Excel',
    importing: 'Importando datos...',
    importSuccess: 'Contenido importado correctamente.',
    importError: 'Fallo al importar el contenido.',

    // --- Auth & Settings ---
    settings: 'Ajustes',
    language: 'Idioma',
    changePassword: 'Cambiar Contraseña',
    logout: 'Cerrar Sesión',
    currentPassword: 'Contraseña Actual',
    newPassword: 'Nueva Contraseña',
    confirmPassword: 'Confirmar Nueva Contraseña',
    passwordsDoNotMatch: 'Las contraseñas no coinciden.',
    passwordChanged: 'Contraseña actualizada correctamente.',

    // --- Analytics ---
    performanceAnalytics: 'Rendimiento',
    analyzeProgress: 'Analiza tu progreso y estadísticas',
    configuration: 'Configuración',
    groupBy: 'Agrupar vista por',
    filterBySubject: 'Filtrar Asignatura',
    allSubjects: 'Todas las Asignaturas',
    clearFilter: 'Limpiar Filtro',
    percentageCorrect: '% de Aciertos',
    noData: 'No hay datos suficientes para mostrar gráficas.',
    breakdown: 'Desglose Detallado',
    hits: 'Aciertos',
    attempts: 'Intentos',
    selectSubject: 'Seleccionar Asignatura',
    globalReset: 'Borrado Global',
    confirmGlobalReset: '¿Estás seguro de borrar TODAS las estadísticas de TODAS las asignaturas? Esto dejará el historial de exámenes vacío.',
    topic: 'Tema',
    concept: 'Concepto',
    group: 'Grupo',
    question: 'Pregunta',

    // --- Backup ---
    backupManagement: 'Gestión de Copias',
    generateBackup: 'Generar Nueva Copia',
    noBackups: 'No hay copias disponibles.',
    processing: 'Procesando...',
    restoreConfirm: '⚠️ ESTO BORRARÁ TODOS LOS DATOS ACTUALES y restaurará la copia seleccionada. ¿Continuar?',
    restoreSuccess: 'Restauración completada con éxito.',
    restoreFail: 'Falló la restauración.',
    downloadError: 'No se pudo descargar el archivo.',
    auto: 'AUTO',
    manual: 'MANUAL',

    // --- Group Detail ---
    accessCode: 'Código de Acceso',
    copyCode: 'Copiar código',
    shareCode: 'Compartir Código',
    codeCopied: 'Código de acceso copiado al portapapeles.',
    viewStats: 'Ver Estadísticas',
    deleteGroup: 'Eliminar Grupo',
    deleteGroupConfirm: '¿Estás seguro de que quieres eliminar este grupo?',

    // --- Manage Groups ---
    teachingManagement: 'Gestión Docente',
    subjects: 'Asignaturas',
    touchToOrder: 'Toca para ordenar temas',
    myGroups: 'Mis Grupos',
    otherGroups: 'Otros Grupos',
    noSubjects: 'No hay asignaturas disponibles.',
    noGroups: 'No has creado ningún grupo.',
    createGroup: 'Crear Grupo',
    createSubject: 'Crear Asignatura',
    newGroup: 'Nuevo Grupo',
    newSubject: 'Nueva Asignatura',
    subject: 'Asignatura',
    groupName: 'Nombre del Grupo',
    name: 'Nombre',
    description: 'Descripción',
    spanishVersion: '🇪🇸 Versión Español',
    englishVersion: '🇬🇧 English Version',
    exampleGroup: 'Ej: Grupo A - Mañana',
    exampleSubject: 'Ej: Matemáticas',

    // --- Manage Content ---
    academicContent: 'Contenido Académico',
    topics: 'Temas',
    concepts: 'Conceptos',
    noContent: 'No hay contenido creado.',
    relatedTo: 'Relacionado con',
    manageTopics: 'Gestionar Temas',
    linkedTopicsInfo: 'Los temas seleccionados aparecen primero en el orden actual.',

    // --- Manage Questions ---
    questions: 'Preguntas',
    newQuestion: 'Nueva',
    statement: 'Enunciado',
    context: 'Contexto',
    questionType: 'Tipo de Pregunta',
    multipleChoice: 'Opción Múltiple',
    trueFalse: 'Verdadero / Falso',
    selectTopic: 'Selecciona un tema.',
    selectTopicError: 'Selecciona al menos un tema.',
    answers: 'Respuestas',
    option: 'Opción',
    addOption: 'Añadir Opción',
    correct: 'Correcta',
    missingStatement: 'El enunciado es obligatorio.',
    missingCorrect: 'Marca al menos una respuesta correcta.',
    missingTranslation: 'Faltan traducciones al inglés.',
    saved: 'Guardado correctamente.',
    new: 'Nueva',

    // --- Manage Users ---
    users: 'Usuarios',
    manageInvite: 'Gestiona e invita a nuevos miembros',
    invite: 'Invitar',
    createUser: 'Crear Usuario',
    username: 'Nombre de Usuario',
    role: 'Rol',
    admin: 'Administrador (SuperUser)',
    teacher: 'Profesor', // Used in modal
    accessDenied: 'Acceso Denegado',
    noPerms: 'No tienes permisos para gestionar usuarios.',
    deleteUserConfirm: '¿Estás seguro de que quieres eliminar a',
    userCreated: 'Usuario creado. Contraseña temporal:',
    tempPasswordHint: 'Contraseña temporal: ',
    emailInvalid: 'Introduce un correo electrónico válido.',
    passwordGenError: 'No se pudo generar la contraseña a partir del correo.',

    // --- Topic Detail ---
    epigraphs: 'Epígrafes',
    noEpigraphs: 'No hay epígrafes definidos.',
    deleteEpigraphConfirm: '¿Seguro que quieres eliminar este epígrafe?',
  },
};